{
  "hash": "141cb584422eb0177476e21a66031f14",
  "result": {
    "markdown": "---\ntitle: \"\"\nauthor: \"\"\ndate: \"2023-02-15\"\nformat:\n  bookup-html:\n    embed-fonts: false\ntoc: false\n---\n\n\n## Chapter 02: Probability\n\n## Problem 2.1\n\n**When rolling two dice, what is the probability that one die is twice the other?**\n\nBesides the classical way of enumerating all events outcomes, we can also tackle this problem in the following way:\n\nlet's consider two dice - one black and one white. The event that one die shows twice what the other die shows can be thought of as the union of two events: either the black die shows twice what the white die shows (Event A), or the white die shows twice what the black die shows (Event B). These two events are mutually exclusive, so the probability of either event happening is the sum of the probabilities of each event happening.\n\nNow, let's suppose we roll the black die first and then the white die. If the black die shows an odd number, then we know that Event A cannot happen. However, if the black die shows an even number, there is exactly one number on the white die that will result in Event A happening. Since there are n possible numbers on a die (assuming n is even), the probability of Event A happening is $\\frac{1}{2} \\cdot \\frac{1}{n}$.\n\nBy symmetry, the probability of Event B happening is also $\\frac{1}{2} \\cdot \\frac{1}{n}$. Therefore, the probability of either Event A or Event B happening is $P(A \\cup B) = 2 \\cdot \\frac{1}{2} \\cdot \\frac{1}{n}$.\n\ncomming back to our particular case, it means:\n\n$$\nP(E) = 2 \\cdot \\frac{1}{2} \\cdot \\frac{1}{6} = \\frac{1}{6}\n$$\n\n\nwe can simulate this experiment in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-1_e93b24a9d35a220e01f9c291e948bdd2'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    die_1 <- sample(x = 1:6, size = 1, replace = TRUE)\n    die_2 <- sample(x = 1:6, size = 1, replace = TRUE)\n    (die_1 == 2 * die_2) | (die_2 == 2 * die_1)\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.16729\n```\n:::\n:::\n\n\n## Problem 2.2\n\n**Consider an experiment where you roll two dice, and subtract the smaller value from the larger value (getting 0 in case of a tie).**\n\na. What is the probability of getting 0?\nb. What is the probability of getting 4?\n\n### Part (a)\n\nThe probability of getting 0 is the probability of getting a tie. This is the probability of getting the same number on both dice. \n\n$$\nE = \\{(1,1), (2,2), (3,3), (4,4), (5,5), (6,6) \\}\n$$ \n\nand we have $6 \\cdot 6 = 36$ possible outcomes. So: \n\n$$\nP(E) = \\frac{6}{36} = \\frac{1}{6}\n$$\n\nwe can simulate this experiment in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-2_0afddf60c8efc639655e2972439f9de1'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    die_1 <- sample(x = 1:6, size = 1, replace = TRUE)\n    die_2 <- sample(x = 1:6, size = 1, replace = TRUE)\n    die_1 == die_2\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.16885\n```\n:::\n:::\n\n\n### Part (b)\n\nThe probability of getting 4 is the probability of getting a difference of 4.\n\n $$\n E = \\{(1,5), (5,1), (2,6), (6,2) \\}\n $$\n\nand we have $6 \\cdot 6 = 36$ possible outcomes. So:\n\n$$\nP(E) = \\frac{4}{36} = \\frac{1}{9}\n$$\n\nwe can simulate this experiment in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-3_c13b8e2a1f812f790921706b20853f92'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    die_1 <- sample(x = 1:6, size = 1, replace = TRUE)\n    die_2 <- sample(x = 1:6, size = 1, replace = TRUE)\n    abs(die_1 - die_2) == 4\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.11138\n```\n:::\n:::\n\n\n## Problem 2.3\n\n**A hat contains slips of paper numbered 1 through 6. You draw two slips of paper at random from the hat, without replacing the first slip into the hat.**\n\na. Write out the sample space $S$ for this experiment.\nb. Write out the event $E$ \"the sum of the numbers on the slips of paper is 4\".\nc. Find $P(E)$.\nd. Let $F$ be the event \"the larger number minus the smaller number is 0\". What is $P(F)$?\n\n### Part (a) \n\nWe can write the sample space as: \n\n$$\nS = \\{(1,2), (1,3), \\cdots , (6,5) \\}\n$$\n\n### Part (b)\n\nWe can write the event as:\n\n$$\nE = \\{(1,3), (3,1) \\}\n$$\n\n### Part (c)\n\nWe have $6 \\cdot 5 = 30$ possible outcomes. So:\n\n$$\nP(E) = \\frac{2}{30} = \\frac{1}{15}\n$$ \n\nwe can simulate it in R as follows:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-4_ce1d75394c2627481c357a5909199c60'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    hat <- sample(x = 1:6, size = 2, replace = FALSE)\n    sum(hat) == 4\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.06602\n```\n:::\n:::\n\n\n### Part (d)\n\nSince we cannot draw the same number twice:\n\n$$\nF = \\emptyset\n$$\n\n$$\nP(F) = 0\n$$\n\n## Problem 2.4\n\n**Suppose there are two boxes and each contain slips of papers numbered 1-8. You draw one number at random from each box.**\n\na. Estimate the probability that the sum of the numbers is 8.\nb. Estimate the probability that at least one of the numbers is a 2.\n\n### Part (a)\n\nThere are $8 \\cdot 8 = 64$ possible outcomes. The number of outcomes where the sum is 8 is:\n\n$$ \nE = \\{(1,7), (2,6), \\cdots, (7,1) \\}\n$$ \nand the probability is:\n\n$$\nP(E) = \\frac{7}{64}\n$$\n\nWe can simulate this experiment in R as follows:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-5_76a26b50e7bba1b287caa403b1d250dd'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    box_1 <- sample(x = 1:8, size = 1, replace = TRUE)\n    box_2 <- sample(x = 1:8, size = 1, replace = TRUE)\n    sum(box_1 + box_2) == 8\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.10945\n```\n:::\n:::\n\n\n### Part (b)\n\nSimilarly, the number of outcomes where at least one of the numbers is 2 is:\n\n$$\nE = \\{(1,2), (2,1), (2,2), (2,3), \\cdots, (8,2) \\}\n$$ \n\nand the probability is: \n\n$$\nP(E) = \\frac{15}{64}\n$$\n\nWe can simulate this experiment in R as follows:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-6_0866e2669c7d8bceff7f6bb8a5c0aed8'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    box_1 <- sample(x = 1:8, size = 1, replace = TRUE)\n    box_2 <- sample(x = 1:8, size = 1, replace = TRUE)\n    box_1 == 2 | box_2 == 2\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.23232\n```\n:::\n:::\n\n\n## Problem 2.5\n\n**Suppose the proportion of M&M’s by color is:** \n\n| Color   | Proportion |\n|---------|------------|\n| Yellow  | 0.14       |\n| Red     | 0.13       |\n| Orange  | 0.20       |\n| Brown   | 0.12       |\n| Green   | 0.20       |\n| Blue    | 0.21       |\n\na. What is the probability that a randomly selected M&M is not green?\nb. What is the probability that a randomly selected M&M is red, orange, or yellow?\nc. Estimate the probability that a random selection of four M&M’s will contain a blue one.\nd. Estimate the probability that a random selection of six M&M’s will contain all six colors.\n\n\n### Part (a)\n\nUsing the law of complement, we have:\n\n$$\nP(\\neg \\text{G}) = 1 - P(\\text{G}) = 0.80\n$$\n\n### Part (b)\n\nWe can use the law of addition to find the probability of getting red, orange, or yellow:\n\n$$\nP(\\text{R} \\cup \\text{O} \\cup \\text{Y}) = P(\\text{R}) + P(\\text{O}) + P(\\text{Y})\n$$\n\n$$\nP(\\text{R} \\cup \\text{O} \\cup \\text{Y})  = 0.13 + 0.20 + 0.14 \n$$\n\n$$\nP(\\text{R} \\cup \\text{O} \\cup \\text{Y})  =  0.47\n$$\n\n### Part (c)\n\nBy the law of complement the probability of not getting a blue is $1 - 0.21 = 0.79$ and the probability of not getting a blue in four selections is $(0.79)^4 = 0.39$. Then the probability of getting at least one blue in four selections is: \n\n- E: at least one blue in four selections\n\n$$\nP(E) = 1 - P(\\neg E) = 1 - 0.39 = 0.61\n$$\n\nWe can simulate this experiment in R as follows:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-7_521c8fd6517d9ac69b05bb3fc70e5818'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    mms <- sample(x = c(\"yellow\", \"red\", \"orange\", \"brown\", \"green\", \"blue\"),\n     size = 4, p = c(0.14, 0.13, 0.20, 0.12, 0.20, 0.21), replace = TRUE)\n    \"blue\" %in% mms\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.61046\n```\n:::\n:::\n\n\n### Part (d)\n\nThe probability of selecting six M&M's that contain all six colors is (consdiering ordering):\n\n- E: All colors with an specific order\n$$\nP(E) = 0.14 \\cdot 0.13 \\cdots 0.21\n$$\n\nwe need to calculate the total number of ways we can select six M&M's from a total of 6 colors, with a sample size of 6.\nThat is 6!. Then the probability is:\n\n- F: All six colors no matter order\n\n$$\nP(F) = 6! \\cdot  P(E) = 0.0132\n$$\n\nWe can simulate this experiment in R as follows:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-8_a53a38c509ae86abdbf28b83382046d2'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    mms <- sample(x = c(\"yellow\", \"red\", \"orange\", \"brown\", \"green\", \"blue\"),\n     size = 6, p = c(0.14, 0.13, 0.20, 0.12, 0.20, 0.21), replace = TRUE)\n    length(unique(mms)) == 6\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01337\n```\n:::\n:::\n\n\n## Problem 2.6\n\n**With the distribution from Problem 2.5, suppose you buy a bag of M&M’s with 30 pieces in it.\nEstimate the probability of obtaining at least 9 Blue M&M’s and at least 6 Orange M&M’s in the bag.**\n\n::: {.callout-warning}\nSince I'm not quite sure on how to calculate this without the binomial distribution, lets go directly with the R simulation\n:::\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-9_683ebffd2088738fff44c00addecb9e4'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    mms <- sample(x = c(\"yellow\", \"red\", \"orange\", \"brown\", \"green\", \"blue\"),\n     size = 30, p = c(0.14, 0.13, 0.20, 0.12, 0.20, 0.21), replace = TRUE)\n    sum(mms == \"blue\") >= 9 & sum(mms == \"orange\") >= 6\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.06586\n```\n:::\n:::\n\n## Problem 2.7\n\n**Blood types O, A, B, and AB have the following distribution in the United States:**\n\n| Type          | A    | AB     | B     | O     | \n|---------------|------|--------|-------|-------|\n| Probability   | 0.40 | 0.04   | 0.11  | 0.45  |\n\n**What is the probability that two randomly selected people have the same blood type?**\n\nSince getting the same blood type is an independent event, we can calculate the probability of getting the same blood type by multiplying the probability of getting each blood type. That is:\n\n- E: Two randomly selected people have the same blood type\n\n$$\nP(E) =  0.40^2 + \\cdots + 0.45^2 = 0.3762\n$$\n\nWe can simulate this experiment in R as follows:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-10_2f70e1db108c469b285a646f38f6aefc'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    person_1 <- sample(x = c(\"A\", \"AB\", \"B\", \"O\"),\n     size = 1, p = c(0.40, 0.04, 0.11, 0.45), replace = TRUE)\n    person_2 <- sample(x = c(\"A\", \"AB\", \"B\", \"O\"),\n     size = 1, p = c(0.40, 0.04, 0.11, 0.45), replace = TRUE)\n\n    person_1 == person_2\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.37671\n```\n:::\n:::\n\n\n## Problem 2.8\n\n**Use simulation to estimate the probability that a 10 is obtained when two dice are rolled.**\n\nBesides the simulation, we can also calculate the probability of getting a 10. The event space is:\n$$\nE = \\{(6,4), (5,5), (4,6)\\}\n$$\n\nAnd the possible outcomes are $6 \\cdot 6 = 36$. Then the probability of getting a 10 is:\n\n$$\nP(\\text{10})  = \\frac{3}{36} = 0.0833\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-11_00f44a82ed59028b89bc0336c178997f'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    dice_1 <- sample(x = 1:6, size = 1, replace = TRUE)\n    dice_2 <- sample(x = 1:6, size = 1, replace = TRUE)\n    dice_1 + dice_2 == 10\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.08238\n```\n:::\n:::\n\n## Problem 2.9\n\n**Estimate the probability that exactly 3 heads are obtained when 7 coins are tossed.**\n\nSince it's a bit long to calculate this one by counting, lets cite and use the definition of the binomial probability\n\n::: {.callout-tip}\nEvents where there are only two possible outcomes that we can classify as success or failure, and where the probability of success is known to us as $p$ are called binomial events. When we repeat such events several times, the probability to find $r$ successes in $n$ such repetitions can be calculated by using the expression:\n\n$$\nP(r) = \\binom{n}{r} p^r (1-p)^{n-r}\n$$\n\nwhere $\\binom{n}{r}$ is the binomial coefficient, which is the number of ways of selecting $r$ objects from a set of $n$ objects,\nwhere the order of selection does not matter.\n:::\n\nKnowing that, we can calculate the probability of getting exactly 3 heads in 7 tosses:\n\n- E: Exactly 3 heads\n$$\nP(E) = \\binom{7}{3} (0.5)^3 (0.5)^{7-3} = 0.273\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-12_504112005b144e830bc0e064897ac87b'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    tosses <- sample(x = c(\"H\", \"T\"), size = 7, replace = TRUE)\n    sum(tosses == \"H\") == 3\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.27075\n```\n:::\n:::\n\n\nWe can extend this question by asking what is the probability that at least 3 heads are obtained when 7 coins are tossed.\nTo solve this problem we need to find the probabilities that $r$ could be $3,4,5,6,7$ to satisfy the condition \"at least\".\n\n- F: At least 3 heads\n\n$$\nP(F) = \\sum_{r=3}^{7}  \\binom{7}{r} (0.5)^r (0.5)^{7-r}\n$$\n\n| $r$         | $P(F)$                 |\n|-------------|----------------------------------------------|\n| for $r = 3$ | $\\binom{7}{3} (0.5)^3 (0.5)^{4} = 0.2734375$ |\n| for $r = 4$ | $\\binom{7}{4} (0.5)^4 (0.5)^{3} = 0.2734375$ |\n| for $r = 5$ | $\\binom{7}{5} (0.5)^5 (0.5)^{2} = 0.1640625$ |\n| for $r = 6$ | $\\binom{7}{6} (0.5)^6 (0.5)^{1} = 0.0546875$ |\n| for $r = 7$ | $\\binom{7}{7} (0.5)^7 (0.5)^{0} = 0.0078125$ |\n\n$$\nP(F) = 0.273 + \\cdots + 0.007 = 0.773\n$$\n\nWe could also have calculated this by using the complement of the probability of getting at most 2 heads.\n\n- G: At most 2 heads\n$$\nP(F) = 1 - P(G) \n$$\n\n$$\nP(F) = 1 - \\sum_{r=0}^{2} \\binom{7}{r} (0.5)^r (0.5)^{7-r}\n$$\n\n| $r$         | $P(\\text{at most 2 heads})$                  |\n|-------------|----------------------------------------------|\n| for $r = 0$ | $\\binom{7}{0} (0.5)^0 (0.5)^{7} = 0.0078125$ |\n| for $r = 1$ | $\\binom{7}{1} (0.5)^1 (0.5)^{6} = 0.0546875$ |\n| for $r = 2$ | $\\binom{7}{2} (0.5)^2 (0.5)^{5} = 0.1640625$ |\n\n$$\nP(F) = 1 - 0.225 = 0.773\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-13_b9dcb24df1e76e031b6ec371b07ce401'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    tosses <- sample(x = c(\"H\", \"T\"), size = 7, replace = TRUE)\n    sum(tosses == \"H\") >= 3\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.77311\n```\n:::\n:::\n\n## Problem 2.10\n\n**Estimate the probability that the sum of five dice is between 15 and 20, inclusive.**\n\nWe need to count the number of ways that we can roll five dice and get a sum between 15 and 20, and divide that by the total number of possible outcomes when rolling five dice. Since it is a bit long to count all possible combinations of $(a,b,c,d,e)$ where $a+b+c+d+e \\in [15,20]$ We are going directly with the simulation. \n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-14_cf460c16e85803f1277c3398088974cf'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    dice <- sample(x = 1:6, size = 5, replace = TRUE)\n    sum(dice) >= 15 & sum(dice) <= 20\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.55585\n```\n:::\n:::\n\n\n## Problem 2.11\n\n**Suppose a die is tossed repeatedly, and the cumulative sum of all tosses seen is maintained.  Estimate the probability that the cumulative sum ever is exactly 20. (Hint: the function cumsum computes the cumulative sums of a vector.)**\n\nAgain, we are going directly wit the simulation due the overwhelming amount of combinations. We know that 20 is the maximum number of tosses that could have a cumulative sum of 20. So doing a sample of 20 rolls will be enough to get a good estimate.\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-15_0f8a2eb13e6ab45d1fc0f0d3d5a3e368'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    tosses <- sample(x = 1:6, size = 20, replace = TRUE)\n    cumulative_sum <- cumsum(tosses)\n    any(cumulative_sum == 20)\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.28733\n```\n:::\n:::\n\n\n## Problem 2.12\n\n**(Rolling two dice)**\n\na. Simulate rolling two dice and adding their values. Perform 10,000 simulations and make a bar chart showing how many of each outcome occurred.\n\nb. You can buy trick dice, which look (sort of) like normal dice. One die has numbers 5, 5, 5, 5, 5, 5. The other has numbers 2, 2, 2, 6, 6, 6. Simulate rolling the two trick dice and adding their values. Perform 10,000 simulations and make a bar chart showing how many of each outcome occurred.\n\nc. Sicherman dice also look like normal dice, but have unusual numbers. One die has numbers 1, 2, 2, 3, 3, 4. The other has numbers 1, 3, 4, 5, 6, 8. Simulate rolling the two Sicherman dice and adding their values. Perform 10,000 simulations and make a bar chart showing how many of each outcome occurred. How does your answer compare to part (a)?\n\n\n### Part (a)\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-16_a0dd129753a5b99955baff4ea8c6b7b9'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\noutcomes <- replicate(10000, {\n    dice_1 <- sample(x = 1:6, size = 1, replace = TRUE)\n    dice_2 <- sample(x = 1:6, size = 1, replace = TRUE)\n    dice_1 + dice_2\n})\ndf <- data.frame(outcomes)\nggplot(data = df, mapping = aes(outcomes), fill = \"transparent\") +\ngeom_histogram(bins = 11, fill = \"transparent\", color = \"black\")\n```\n\n::: {.cell-output-display}\n![](probability_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n### Part (b)\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-17_71d3cd024b695b4f00f28f911d23c16e'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\noutcomes <- replicate(10000, {\n    dice_1 <- sample(x = c(5, 5, 5, 5, 5, 5), size = 1, replace = TRUE)\n    dice_2 <- sample(x = c(2, 2, 2, 6, 6, 6), size = 1, replace = TRUE)\n    dice_1 + dice_2\n})\ndf <- data.frame(outcomes)\nggplot(data = df, mapping = aes(outcomes), fill = \"transparent\") +\ngeom_histogram(bins = 11, fill = \"transparent\", color = \"black\")\n```\n\n::: {.cell-output-display}\n![](probability_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n### Part (c)\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-18_2b327f7ad05dc1a5e9a58da478e13658'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\noutcomes <- replicate(10000, {\n    dice_1 <- sample(x = c(1, 2, 2, 3, 3, 4), size = 1, replace = TRUE)\n    dice_2 <- sample(x = c(1, 3, 4, 5, 6, 8), size = 1, replace = TRUE)\n    dice_1 + dice_2\n})\ndf <- data.frame(outcomes)\nggplot(data = df, mapping = aes(outcomes), fill = \"transparent\") +\ngeom_histogram(bins = 11, fill = \"transparent\", color = \"black\")\n```\n\n::: {.cell-output-display}\n![](probability_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nThey have the same distribution.\n\n## Problem 2.13\n\n**In a room of 200 people (including you), estimate the probability that at least one other person will be born on the same day as you.**\n\nwe can use the complement rule and calculate the probability that none of the other 199 people share the same birthday as me. Assuming that birthdays are uniformly distributed across all 365 days of the year (ignoring leap years), the probability that any given person in the room was not born on the same day as me is:\n\n- E: No one else has the same birthday as you\n\n$$\nP(E) = \\left(\\frac{1}{365}\\right)^{199} = 0.58\n$$\n\nAnd the probability that at least one other person has the same birthday as you is:\n\n- F: At least one other person has the same birthday as you\n\n$$ \nP(F) = 1 - P(E) = 0.42\n$$\n\nwe can simulate this in R as follow:\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-19_51078a4a0313378bd1377900b669d3f6'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    my_birthday <- sample(x = 1:365, size = 1, replace = TRUE)\n    other_people_birthdays <- sample(x = 1:365, size = 199, replace = TRUE)\n    any(other_people_birthdays == my_birthday)\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.42299\n```\n:::\n:::\n\n\n## Problem 2.14\n\n**In a room of 100 people, estimate the probability that at least two people were not only born on the same day,\nbut also during the same hour of the same day. (For example, both were born between 2 and 3.)**\n\nAssuming each person birth is uniformly distributed across all 24 hours of the day, and all 365 days of the year (ignoring leap years). The probability that any two people were born during the same hour of the same day is:\n\n- E: Two people were born during the same hour of the same day\n\n$$\nP(E) = \\frac{1}{24} \\cdot \\frac{1}{365} = 0.0001\n$$\n\nThen the probability that none of the 100 people were born on the same day and during the same hour can be expressed as:\n\nF: None of the 100 people were born on the same day and during the same hour\n\n$$\nP(F) = \\left(1 - P(E)\\right)^{\\binom{100}{2}} = 0.5683\n$$\n\nfinally the probability that at least two people were born during the same hour of the same day is:\n\n- G: At least two people were born during the same hour of the same day\n\n$$\nP(G) = 1 - P(F) = 0.4316\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-20_99a473283436afdc319c38b78b4d73ba'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    birthdays <- sample(x = 1:(365 * 24), size = 100, replace = TRUE)\n    sum(duplicated(birthdays)) >= 1\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.42947\n```\n:::\n:::\n\n\n## Problem 2.15\n\n**Assuming that there are no leap-day babies and that all birthdays are equally likely, estimate the probability that at least three people have the same birthday in a group of 50 people. (Hint: try using table.)**\n\nThe probability of the birthday problem becomes increasingly complicated with more people, as the complementary event includes a larger number of possibilities that need to be accounted for. For example, for three people, the complementary event not only includes the possibility that all three birthdays are distinct, but also the possibilities of having one pair with the rest distinct, two pairs with the rest distinct, and so on. Calculating the exact value can be quite complicated.\n\n::: {.callout-warning}\nI'm going to use the Poisson approximation to calculate the probability of the birthday problem. The Poisson approximation is a good approximation for large values of $n$ and small values of $p$. In this case, $n = 50$ and $p = \\frac{1}{365}$. However, the autor maybe want us to only simulate the problem, because at this chapter we are not supposed to know the Poisson approximation.\n:::\n\nOne way to approach this is by considering every group of three people and calling it a \"success\" if they all share the same birthday.\nThis can be modeled as a Poisson distribution, where the expected number of \"successes\" is the number of groups of three people times the probability that three people share the same birthday.\n\nThe total number of successes is approximately Poisson with mean value $\\frac{\\binom{50}{3}}{365^{2}}$.\nHere $\\binom{50}{3}$ is the number of triples, and $\\frac{1}{365^{2}}$ is the chance that any particular triple is a success.\nThe probability of getting at least one success is obtained from the Poisson distribution:\n\n- E: At least three people have the same birthday in a group of 50 people\n$$\nP(E) \\approx 1 - \\exp \\left(- \\frac{\\binom{50}{3}}{365^{2}}\\right) = 0.136\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-21_1e43c462d9fc9684bf72540a8dc8e5a2'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    birthdays <- sample(x = 1:365, size = 50, replace = TRUE)\n    birthday_table <- table(birthdays)\n    length(birthday_table[birthday_table >= 3])\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1339\n```\n:::\n:::\n\n\n## Problem 2.16\n**If 100 balls are randomly placed into 20 urns, estimate the probability that at least one of the urns is empty.**\n\nThe probability of choose an specific urn is $\\frac{1}{20}$ then the probability of not choose an specific urn is $\\frac{19}{20}$\nand the probability of not choose an specific urn 100 times is $\\left(\\frac{19}{20}\\right)^{100}$. To get the probability of at least one urn is empty we need to multiply this by the number of urns:\n\n$$\nP(E) = \\left(\\frac{19}{20}\\right)^{100} \\cdot 20 = 0.1184\n$$\n\nWe can simulate this in  R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-22_85aa43022e7fd40e8fa31804b64a9cfc'}\n\n```{.r .cell-code}\nevent  <- replicate(100000, {\n    selected_urns <- sample(x =  1:20, size = 100, replace = TRUE)\n    length(unique(selected_urns)) < 20\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.11309\n```\n:::\n:::\n\n\n## Problem 2.17\n**A standard deck of cards has 52 cards, four each of 2,3,4,5,6,7,8,9,10,J,Q,K,A. In blackjack, a player gets two cards and adds their values. Cards count as their usual numbers, except Aces are 11 (or 1), while K, Q, J are all 10.**\n\na. “Blackjack” means getting an Ace and a value 10 card. What is the probability of getting a blackjack?\nb. What is the probability of getting 19? (The probability that the sum of your cards is 19, using Ace as 11)\n\n### Part (a)\n\nWe can see it as follow:\n\n1) We're dealt an 11, and then a 10. (11 + 10 = 21)\n2) We're dealt a 10, and then an 11. (10 + 11 = 21)\n\n* Option 1:\n\nFirst event (getting an 11 card): There are 4 aces in a pack, and we've got a full pack (52 cards), so the probability of getting one of the aces first is 4 out of 52 $\\frac{4}{52}$. Second event (getting a 10 card): There are 16 cards worth 10 in a pack (4 of each of 10, J, Q, K), but we've already got one of the cards from the back, so the probability of getting a 10 now is 16 out of 51 $\\frac{16}{51}$. We want event 1 AND event 2 to happen, so we have to multiply the probabilities: $\\frac{4}{52} \\cdot \\frac{16}{51} = \\frac{64}{2652}$\n\n* Option 2:\n\nFirst event (getting a 10 card): There are 16 cards worth 10, as before, but this time we've got a full pack, so the probability is $\\frac{16}{52}$. Second event (getting an 11 card): There are 4 aces, as before, but this time we've got rid of one card, so the probability is $\\frac{4}{51}$. Again, we want event 1 AND event 2 to happen: $\\frac{4}{51} \\cdot \\frac{16}{52} = \\frac{64}{2652}$\n \nNow, we want either option 1 OR option 2to happen (because either way will give us a blackjack). \nThere's an OR there, so we've got to add the two probabilities together: \n\n- E: Getting a blackjack\n$$\nP(E) = \\frac{64}{2652} + \\frac{64}{2652}\n$$\n\n$$\nP(E) = 0.048\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-23_54b0c19d6364bfad3336b8abc2a82175'}\n\n```{.r .cell-code}\ndeck <- c(\"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"10\", \"10\", \"10\", \"A\")\nevent  <- replicate(100000, {\n    cards <- sample(x = deck, size = 2, replace = TRUE)\n    (cards[1] == \"A\" && cards[2] == \"10\") ||\n    (cards[1] == \"10\" && cards[2] == \"A\")\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04763\n```\n:::\n:::\n\n\n### Part (b)\n\nWe can see it as follow:\n\n1) We're dealt an 11, and then a 8. (11 + 8 = 19)\n2) We're dealt a 8, and then an 11. (11 + 8 = 19)\n3) We're dealt an 10 and a 9. (10 + 9 = 19)\n4) We're dealt a 9 and a 10. (9 + 10 = 19)\n\nSo we can calculate the probability similarly as the previous problem:\n\n- E: Getting 19\n$$\nP(E) = 2 \\cdot \\frac{4}{52} \\cdot \\frac{4}{51} + 2 \\cdot \\frac{16}{52} \\cdot \\frac{4}{51}\n$$\n\n$$\nP(E) = 0.060\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-24_9016e35aafbb467cd6981a3d3bca300c'}\n\n```{.r .cell-code}\ndeck <- c(\"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"10\", \"10\", \"10\", \"A\")\nevent  <- replicate(100000, {\n    cards <- sample(x = deck, size = 2, replace = TRUE)\n    (cards[1] == \"9\" && cards[2] == \"10\") ||\n    (cards[1] == \"10\" && cards[2] == \"9\") ||\n    (cards[1] == \"A\" && cards[2] == \"8\")  ||\n    (cards[1] == \"8\" && cards[2] == \"A\")\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05815\n```\n:::\n:::\n\n\n## Problem 2.18\n\n**Deathrolling in World of Warcraft works as follows. Player 1 tosses a 1000-sided die. Say they get $x_{1}$. Then player 2 tosses a die with $x_{1}$ sides on it. Say they get  $x_{2}$. Player 1 tosses a die with $x_{2}$ sides on it. This pattern continues until a player rolls a 1. The player who loses is the player who rolls a 1. Estimate via simulation the probability that a 1 will be rolled on the 4th roll in deathroll.**\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-25_45a41b1067aea91f404c6f478748e778'}\n\n```{.r .cell-code}\nevent <- replicate (100000, {\n    x1 <- sample(x = 1:1000, size = 1, replace = TRUE)\n    x2 <- sample(x = 1:x1, size = 1, replace = TRUE)\n    x3 <- sample(x = 1:x2, size = 1, replace = TRUE)\n    x4 <- sample(x = 1:x3, size = 1, replace = TRUE)\n\n    x4 == 1\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.07554\n```\n:::\n:::\n\n\n## Problem 2.19\n\n**In the game of Scrabble, players make words using letter tiles. The data set `fosdata::scrabble` contains all 100 tiles. Estimate the probability that a player’s first seven tiles contain no vowels. (Vowels are A, E, I, O, and U.)**\n\nLetter tiles in Scrabble are distributed as follow:\n\n| Frequency | Letters                                 |\n|-----------|-----------------------------------------|\n| 1         | Q, Z, J, X, K                           |\n| 2         | B, C, F, H, M, P, V, W, Y, (black tile) |\n| 3         | G                                       |\n| 4         | D, L, S, U                              |\n| 6         | N, R, T                                 |\n| 8         | O                                       |\n| 9         | A, I                                    |\n| 12        | E                                       |\n\nThe total number of vowels is:\n\n$$\nN_{\\text{vowels}} = 9 + 12 + 9 + 8 + 4 = 42\n$$\n\nThat means there is a total of 58 non vowels in the scrabble set, so the probability of getting no vowels is:\n\n$$\nP(E) = \\frac{58\\cdot 57 \\cdots 52}{100 \\cdot 99 \\cdots 94}\n$$\n\n$$\nP(E) = 0.019\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-26_e260452df42ed2b7899f2ba0f377d63b'}\n\n```{.r .cell-code}\nlibrary(fosdata)\nevent <- replicate(100000, {\n    tiles <- sample(x = fosdata::scrabble$piece, size = 7, replace = FALSE)\n    !any(tiles %in% c(\"A\", \"E\", \"I\", \"O\", \"U\"))\n})\n\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.0195\n```\n:::\n:::\n\n\n## Problem 2.20\n\n**Two dice are rolled.**\n\na. What is the probability that the sum of the numbers is exactly 10?\nb. What is the probability that the sum of the numbers is at least 10?\nc. What is the probability that the sum of the numbers is exactly 10, given that it is at least 10?\n\n### Part (a)\n\nThe probability of getting a 10 is:\n\n$$\nE = \\{ (6,4), (4,6), (5,5) \\}\n$$\n\n$$\nP(E) = \\frac{3}{36} = 0.083\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-27_2c3437a0fe44c2fa419d1853970b8439'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    dice1 <- sample(x = 1:6, size = 1, replace = TRUE)\n    dice2 <- sample(x = 1:6, size = 1, replace = TRUE)\n    dice1 + dice2 == 10\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.08453\n```\n:::\n:::\n\n\n### Part (b)\n\nThe probability of getting a 10 or more is:\n\n$$\nE = \\{ (6,6), (6,5), \\cdots, (5,5) (4,6)\\}\n$$\n\n$$\nP(E) = \\frac{6}{36} = 0.167\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-28_79bd0c7d704cba48e955af50bdfd8407'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    dice1 <- sample(x = 1:6, size = 1, replace = TRUE)\n    dice2 <- sample(x = 1:6, size = 1, replace = TRUE)\n    dice1 + dice2 >= 10\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.16767\n```\n:::\n:::\n\n\n### Part (c)\n\n- A: The sum of the numbers is exactly 10\n- B: The sum of the numbers is at least 10\n\n$$\nP(A|B) = \\frac{P(A \\cap B)}{P(B)}\n$$\n\n$$\nP(A|B) = \\frac{\\frac{3}{36}}{\\frac{6}{36}} = \\frac{1}{2} \n$$\n\n\n## Problem 2.21\n\n**A hat contains six slips of paper with the numbers 1 through 6 written on them. Two slips of paper are drawn from the hat (without replacing), and the sum of the numbers is computed.**\n\na. What is the probability that the sum of the numbers is exactly 10?\nb. What is the probability that the sum of the numbers is at least 10?\nc. What is the probability that the sum of the numbers is exactly 10, given that it is at least 10?\n\n### Part (a)\n\nThe probability of getting a 10 is:\n\n$$\nE = \\{ (6,4), (4,6) \\}\n$$\n\nAnd we have 6 (first draw) times 5 (second draw) = 30 ways to draw two slips of paper.\n\n$$\nP(E) = \\frac{2}{30} = 0.067\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-29_290afa1d7289feb482f56036f222eed9'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    slips <- sample(x = 1:6, size = 2, replace = FALSE)\n    sum(slips) == 10\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.06729\n```\n:::\n:::\n\n\n### Part (b)\n\nThe probability of getting a 10 or more is:\n\n$$\nE = \\{ (4,6), (5,6), (6, 4), (6,5)\\}\n$$\n\nAs like before,\n\n$$\nP(E) = \\frac{4}{30} = 0.133\n$$\n\nWe can simulate this in R as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-30_8b71f208eaafdee0075bcb0fe84076eb'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    slips <- sample(x = 1:6, size = 2, replace = FALSE)\n    sum(slips) >= 10\n})\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.13328\n```\n:::\n:::\n\n\n### Part (c)\n\n- A: The sum of the numbers is exactly 10\n- B: The sum of the numbers is at least 10\n\n$$\nP(A|B) = \\frac{\\frac{2}{30}}{\\frac{4}{30}} = \\frac{1}{2}\n$$\n\n::: {.callout-warning}\nNote that $P(A \\cap B) = P(A)$ in this and the previous case beacuse \"exactly 10\" is a subset of \"at least 10\".\nIt is not the general case.\n:::\n\n## Problem 2.22\n\n**Roll two dice, one white and one red. Consider these events:**\n\n* $A$: The sum is 7.\n* $B$: The white die is odd.\n* $C$: The red die has a larger number showing than the white.\n* $D$: The dice match (doubles).\n\na. Wich pair(s) of events are disjoint (events $A$ and $B$ are disjoint if $A \\cap B = \\emptyset$ )?\nb. Which pair(s) are independent?\nc. Which pair(s) are neither disjoint nor independent?\n\n### Part (a)\n\nThe following pairs are disjoint:\n\n- $A$ and $D$: None of doubles can sum to 7.\n- $C$ and $D$: None of doubles can have a larger number than the other.\n\n### Part (b)\n\nThe following pairs are independent:\n\n- $A$ and $B$: The sum of the dice is independent of the parity of the white die.\n- $A$ and $C$: The sum of the dice is independent of the relative size of the dice.\n- $B$ and $D$: The parity of the white die is independent of the dice matching.\n\n### Part (c)\n\nThe following pairs are neither disjoint nor independent:\n\n- $B$ and $C$: If the red dice has a larger number than the white, we can only get odd numbers below that number. For example, if the red dice is 4, the white dice can only be 1 or 3. That means $P(A \\cap B) \\neq P(A) \\cdot P(B)$ so the events are not independent.\nbut also they are not disjoint because both events can happen at the same time.\n\n\n## Problem 2.23\n\n**Suppose you do an experiment where you select ten people at random and ask their birthdays.**\n\nHere are three events:\n\n* $A$: all ten people were born in February.\n* $B$: the first person was born in February.\n* $C$: The second person was born in January.\n\na. Which pair(s) of events are disjoint, if any?\nb. Which pair(s) are independent, if any?\nc. What is $P(A | B)$?\n\n### Part (a)\n\nThe following pairs are disjoint:\n\n- $A$ and $C$: If all ten people were born in February, the second person cannot be born in January.\n\n### Part (b)\n\nThe following pairs are independent:\n\n- $B$ and $C$: The first person's birthday is independent of the second person's birthday.\n\n### Part (c)\n\nIt means the probability of all ten people being born in February given that the first person was born in February. Given that $A \\subset B$ we can express it as:\n$$\nP(A|B) = \\frac{P(A \\cap B)}{P(B)} = \\frac{P(A)}{P(B)}\n$$\n\n$$\nP(A|B) = \\frac{\\left(\\frac{1}{12}\\right)^{10}}{\\frac{1}{12}} = 1.93e-10\n$$\n\n## problem 2.24\n\n**Let $A$ and $B$ be events. Show that $P(A \\cup B | B) = 1$ **.\n \n $$\n P(A \\cup B | B) = \\frac{P((A \\cup B) \\cap B)}{P(B)} = \\frac{P(B)}{P(B)} = 1\n $$\n\n## Problem 2.25\n\n**In an experiment where you toss a fair coin twice, define events:**\n\n* $A$: The first toss is heads.\n* $B$: The second toss is heads.\n* $C$: Both tosses are the same.\n\nShow that $A$ and $B$ are independent. Show that $A$ and $C$ are independent. Show that $B$ and $C$ are independent. Show that $A$, $B$, and $C$ are not mutually independent.\n\n\nTo show that $A$ and $B$ are independent, we need to show that $P(A \\cap B) = P(A) \\cdot P(B)$.\n\n- $A \\cap B$: The first toss is heads and the second toss is heads.\n- $A \\cap C$: The first toss is heads and the second toss is heads.\n- $B \\cap C$: The first toss is heads and the second toss is heads.\n- $A \\cap B \\cap C$: The first toss is heads and the second toss is heads.\n\nWe can define the sample space as:\n$$\nS = \\{(H,H), (H, T), (T, H), (T,T) \\}\n$$\n\nAnd the events as:\n\n$$\nA = \\{(H,H), (H, T)\\}\n$$\n\n$$\nB = \\{(H,H), (T, H)\\}\n$$\n\n$$\nC = \\{(H,H), (T, T)\\}\n$$\n\nAnd the intersections as:\n\n$$\nA \\cap B = A \\cap C = B \\cap C = \\{(H,H)\\}\n$$\n\nAnd the probabilities could be calculated as:\n\n$$\nP(A \\cap B) = P(A \\cap C) = P(B \\cap C) = \\frac{1}{4}\n$$\n\n$$\nP(A) = P(B) = P(C) = \\frac{2}{4} = \\frac{1}{2}\n$$\n\n\n- $A$ and $B$ are independent:\n\n$$\nP(A \\cap B) = P(A) \\cdot P(B) \n$$\n\n$$\n\\frac{1}{4} = \\frac{1}{2} \\cdot \\frac{1}{2}\n$$\n\n- $A$ and $C$ are independent:\n\n$$\nP(A \\cap C) = P(A) \\cdot P(C)\n$$\n\n$$\n\\frac{1}{4} = \\frac{1}{2} \\cdot \\frac{1}{2}\n$$\n\n- $B$ and $C$ are independent:\n\n$$\nP(B \\cap C) = P(B) \\cdot P(C)\n$$\n\n$$\n\\frac{1}{4} = \\frac{1}{2} \\cdot \\frac{1}{2}\n$$\n\n- $A$, $B$, and $C$ are not mutually independent:\n\n$$\nP(A \\cap B \\cap C) = P(A) \\cdot P(B) \\cdot P(C)\n$$\n\n$$\n\\frac{1}{4} \\neq \\frac{1}{2} \\cdot \\frac{1}{2} \\cdot \\frac{1}{2}\n$$\n\n\n## Problem 2.26\n\n**Suppose a die is tossed three times. Let $A$ be the event \"the first toss is a 5\", let $B$ be the event \"the first toss is the largest number rolled\" (the \"largest\" can be a tie). Determine, via simulation or otherwise, whether $A$ and $B$ are independent.**\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-31_e3bc19893b1dfb285b568e2f79e499e9'}\n\n```{.r .cell-code}\nevent_a_b <- replicate(100000, {\n  rolls <- sample(x = 1:6, size = 3, replace = TRUE)\n  a <- rolls[1] == 5\n  b <- rolls[1] == max(rolls)\n  a && b\n})\n\na_b <- mean(event_a_b)\n\nevent_a <- replicate(100000, {\n  rolls <- sample(x = 1:6, size = 3, replace = TRUE)\n  rolls[1] == 5\n})\n\na <- mean(event_a)\n\nevent_b <- replicate(100000, {\n  rolls <- sample(x = 1:6, size = 3, replace = TRUE)\n  rolls[1] == max(rolls)\n})\n\nb <- mean(event_b)\n\nprint(paste(\"P(A and B):\", a_b))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"P(A and B): 0.1161\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste(\"P(A) * P(B):\", a * b))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"P(A) * P(B): 0.070339434\"\n```\n:::\n:::\n\n\nAs we can see, the probability of $A \\cap B$ is not equal to the probability of $A$ times the probability of $B$. Therefore, they are not independent.\n\n## Problem 2.27\n\n**Suppose you have two coins that land with heads facing up with common probability $p$ where $0 < p < 1$. One coin is red and the other is white. You toss both coins. Find the probability that the red coin is heads, given that the red coin and the white coin are different. Your answer will be in terms of $p$**\n\n- A: red coin is heads\n- B: white coin is heads\n- C: red coin and white coin are different (i.e., one shows heads and the other shows tails)\n\nWe want to find $P(A|C)$. We can express this probability in terms of conditional probabilities:\n\n$$\nP(A|C) = \\frac{P(A \\cap C)}{P(C)}\n$$\n\nWe know that $P(A) = P(B) = p$ and $P(C) = 2p(1-p)$, since there are two ways in which the coins can be different (red heads, white tails and red tails, white heads), and each of these ways has probability $p(1-p)$. For $P(A \\cap C)$ we can use the fact that $A \\cap C$ means the red coin is heads and the white coin is tails, and there is only one way in which this can happen, so $P(A \\cap C) = p(1-p)$.\n\n$$\nP(A|C) = \\frac{p(1-p)}{2p(1-p)} = \\frac{1}{2}\n$$\n\nwe can simulate this experiment to verify our result:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-32_d11243a6dd30e57be1beb5a8ae7f4c7f'}\n\n```{.r .cell-code}\np <- runif(n = 1, min = 0, max = 1)\nevent_a_and_c <- replicate(100000, {\n    red <- sample(x = c(\"H\", \"T\"), size = 1, replace = TRUE, prob = c(p, 1-p))\n    white <- sample(x = c(\"H\", \"T\"), size = 1, replace = TRUE, prob = c(p, 1-p))\n    red == \"H\" && white != red\n})\n\nevent_c <- replicate(100000, {\n    red <- sample(x = c(\"H\", \"T\"), size = 1, replace = TRUE, prob = c(p, 1-p))\n    white <- sample(x = c(\"H\", \"T\"), size = 1, replace = TRUE, prob = c(p, 1-p))\n    white != red\n})\n\nprob_a_and_c <- mean(event_a_and_c)\nprob_c <- mean(event_c)\nprob_a_and_c / prob_c\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5046218\n```\n:::\n:::\n\n\n## Problem 2.28\n\n**Bob Ross was a painter with a PBS television show, \"The Joy of Painting,\" that ran for 11 years.**\n\na. 91% of Bob’s paintings contain a tree and 85% contain two or more trees. What is the probability that he painted a second tree, given that he painted a tree?\n\nb. 18% of Bob’s paintings contain a cabin. Given that he painted a cabin, there is a 35% chance the cabin is on a lake. What is the probability that a Bob Ross painting contains both a cabin and a lake?\n\n### Part (a)\n\nWe want to find $P(B|A)$, where $A$ is the event \"Bob painted a tree\" and $B$ is the event \"Bob painted a second tree\". We can express this probability in terms of conditional probabilities:\n\n$$\nP(B|A) = \\frac{P(B \\cap A)}{P(A)}\n$$\n\nWe know that $P(A) = 0.91$ and $P(B) = 0.85$. For $P(B \\cap A)$ we can use the fact that $B \\cap A$ means Bob painted a tree and a second tree, and there is only one way in which this can happen, so $P(B \\cap A) = 0.85$.\n\n$$\nP(B|A) = \\frac{0.85}{0.91} = 0.93\n$$\n\n### Part (b)\n\nWe want to find $P(A \\cap B)$, where $A$ is the event \"Bob painted a cabin\", $B$ is the event \"The cabin is on a lake\". We can express this probability in terms of conditional probabilities:\n\n$$\nP(A \\cap B) = P(A)P(B|A)\n$$\n\nWe know that $P(A) = 0.18$ and $P(B|A) = 0.35$, so we can calculate $P(A \\cap B)$ as follows:\n\n$$\nP(A \\cap B) = 0.18 \\cdot 0.35 = 0.063\n$$\n\n## Problem 2.29\n\n**Ultimate frisbee players are so poor they don’t own coins. So, team captains decide which team will play offense first by flipping frisbees before the start of the game. Rather than flip one frisbee and call a side, each team captain flips a frisbee and one captain calls whether the two frisbees will land on the same side, or on different sides. Presumably, they do this instead of just flipping one frisbee because a frisbee is not obviously a fair coin - the probability of one side seems likely to be different from the probability of the other side.**\n\na. Suppose you flip two fair coins. What is the probability they show different sides?\nb. Suppose two captains flip frisbees. Assume the probability that a frisbee lands convex side up is $p$. Compute the probability (in terms of $p$) that the two frisbees match.\nc. Make a graph of the probability of a match in terms of $p$.\nd. One Reddit user flipped a frisbee 800 times and found that in practice, the convex side lands up 45% of the time. When captains flip, what is the probability of “same?” What is the probability of “different?”\ne. What advice would you give to an ultimate frisbee team captain?\nf. Is the two-frisbee flip better than a single-frisbee flip for deciding the offense?\n\n### Part (a)\n\nThe space of outcomes for flipping two fair coins is:\n$$\nS = \\{HH, HT, TH, TT\\}\n$$.\n\nThe event \"the two coins show different sides\" is:\n\n$$\nE = \\{HT, TH\\}\n$$ \n \n so the probability of this event is:\n \n$$\n P(E) = \\frac{2}{4} = \\frac{1}{2}\n$$\n\n### Part (b)\n\nThe probability that a frisbee lands convex side up is $p$ and the probability that it lands concave side up is $1-p$. So the probability of the both frisbee match is:\n\n$$\nP(E) = p^2 + (1-p)^2\n$$\n\n### Part (c)\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-33_e8cdc81e5c6d8b35886227eb55b39191'}\n\n```{.r .cell-code}\np <- seq(0, 1, length.out = 100)\nprob <- p^2 + (1-p)^2\nplot(p, prob, type = \"l\", xlab = \"p\", ylab = \"probability of match\")\n```\n\n::: {.cell-output-display}\n![](probability_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n### Part (d)\n\nThe probability of a match is $p^2 + (1-p)^2$, so the probability of a non-match is $1 - p^2 - (1-p)^2$. If the probability of a convex side up is $0.45$, then the probability of a match is:\n\n$$\nP(\\text{match}) = 0.45^2 + (1-0.45)^2 = 0.505\n$$\n\nand the probability of a non-match is:\n\n$$\nP(\\text{non-match}) = 1 - 0.505 = 0.495\n$$\n\n### Part (e)\n\n Since the probability of match is slightly higher than the probability of non-match, the captains should call \"same\" (assuming that they want to play offence first) but the difference is small enough that it doesn't really matter.\n\n### Part (f)\n\nThe two-frisbee flip is better than a single-frisbee flip for deciding the offense because the probability of match or non-match is almost a fair coin flip, whereas the probability of a single frisbee is more bias towards the concav side.\n\n## Problem 2.30\n\n**Suppose there is a new test that detects whether people have a disease. If a person has the disease, then the test correctly identifies that person as being sick 99.9% of the time (sensitivity of the test). If a person does not have the disease, then the test correctly identifies the person as being well 97% of the time (specificity of the test). Suppose that 2% of the population has the disease. Find the probability that a randomly selected person has the disease given that they test positive for the disease.**\n\nWe can use Bayes' theorem to solve this problem:\n\n$$\nP(H|E) = \\frac{P(E|H)P(H)}{P(E)}\n$$\n\n$P(E)$ is more conveniently expressed as:\n\n$$\nP(E) = P(E|H)P(H) + P(E|\\neg H)P(\\neg H)\n$$\n\nWe know that $P(H) = 0.02$, $P(\\neg H) = 0.98$, $P(E|H) = 0.999$ and $P(E|\\neg H) = 0.03$ (false positives). Then We can calculate $P(H|E)$ as follows:\n\n$$\nP(H|E) = \\frac{0.999 \\cdot 0.02}{0.999 \\cdot 0.02 + 0.03 \\cdot 0.98} = 0.40\n$$\n\n## Problem 2.31\n\n**Suppose that there are two boxes containing marbles. Box 1 contains 3 red and 4 blue marbles. Box 2 contains 2 red and 5 blue marbles. A single die is tossed, and if the result is 1 or 2, then a marble is drawn from box 1. Otherwise, a marble is drawn from box 2.**\n\n![balls](./images/boxballs1.png){fig-align=\"center\"}\n\na. What is the probability that the marble drawn is red?\nb. What is the probability that the marble came from box 1 given that the marble is red?\n\n### Part (a)\n\nWe can define the following events:\n\n- $A$: the die is 1 or 2\n- $B$: the die is 3, 4, 5 or 6\n- $C$: the marble is red\n- $D$: the marble is blue\n\nWe can calculate the probability of the marble using the law of total being red as follows:\n\n$$\nP(C) = P(C|A)P(A) + P(C|B)P(B)\n$$\n\nWe know that $P(A)=\\frac{2}{6}$, $P(B)=\\frac{4}{6}$, $P(C|A)=\\frac{3}{7}$ and $P(C|B)=\\frac{2}{7}$. So we can calculate $P(C)$ as follows:\n\n$$\nP(C) = \\frac{3}{7} \\cdot \\frac{2}{6} + \\frac{2}{7} \\cdot \\frac{4}{6} = \\frac{11}{42} = 0.26\n$$\n\n### Part (b)\n\nWe can use Bayes' theorem to calculate the probability that the marble came from box 1 given that the marble is red:\n\n$$\nP(A|C) = \\frac{P(C|A)P(A)}{P(C)}\n$$\n\nUsing the values from part (a), we can calculate $P(A|C)$ as follows:\n\n$$\nP(A|C) = \\frac{\\frac{3}{7} \\cdot \\frac{2}{6}}{\\frac{11}{42}} = \\frac{6}{11} = 0.54\n$$\n\n## Problem 2.32\n\n**Suppose that you have 10 boxes, numbered 0-9. Box $i$ contains $i$ marbles, and $9-i$ blue marbles.** \n\n![balls](./images/boxballs2.png){fig-align=\"center\"}\n\n**You perform the following experiment. Pick a box at random, draw a marble and record its color. Replace the marble back in the box, and draw another marble from the same box and record its color. Replace the marble back in the box, and draw another marble from the same box and record its color. So, all three marbles are drawn from the same box.**\n\na. If you draw three consecutive red marbles, what is the probability that a fourth marble drawn from the same box will also be red?\nb. If you draw three consecutive red marbles, what is the probability that you chose box 9?\n\n### Part (a)\n \nLet's first calculate the probability of drawing three consecutive red marbles from a box. We will use conditional probability to solve this problem. Let's denote the event of drawing three consecutive red marbles as $R_{3}$, and the event of choosing a box $i$ as $B_{i}$.\n\nThe probability of drawing three consecutive red marbles can be expressed as follows:\n\n$$\nP(R_{3}) = \\sum_{i=0}^{9} P(R_{3}|B_{i})P(B_{i})\n$$\n\nSince we have 10 boxes (numbered 0-9) and we select a box at random, the probability of choosing any box $i$ is:\n\n$$\nP(B_{i}) = \\frac{1}{10}\n$$\n\nNow, let's calculate the probability of drawing three consecutive red marbles given that we have chosen box $i$ represented by $P(R_{3} | B_{i})$. The probability of drawing a red marble on box $i$ is $\\frac{i}{9}$. Since we replace the marble after drawing, the probability remains the same for each draw. Therefore, the probability of drawing three consecutive red marbles from box $i$ is:\n\n$$\nP(R_{3} | B_{i}) = \\left(\\frac{i}{9}\\right)^{3}\n$$\n\nNow, we can calculate the probability of drawing three consecutive red marbles (we can trivially discard $i=0$):\n\n$$\nP(R_{3}) = \\frac{1}{10}  \\cdot \\sum_{i=1}^{9} \\left(\\frac{i}{9}\\right)^{3} = 0.277\n$$\n\nNow, we want to calculate the probability that the fourth marble drawn from the same box will also be red, given that we have drawn three consecutive red marbles. Let's denote this event as $R_{4}$ (for the fourth red marble). We need to compute $P(R_{4} | R_{3})$.\n\nWe can apply Bayes' theorem:\n\n$$\nP(R_{4} | R_{3}) = \\frac{P(R_{3} | R_{4}) \\cdot P(R_{4})}{P(R_{3})}\n$$\n\nWe know that $P(R_{3}) = 0.277$, and $P(R_{3} | R_{4}) = 1$ (because the probability of getting 3 red marbles consecutive given that we have 4 red marbles consecutive is 1). Therefore, the only missing part is $P(R_{4})$ wich can be calculated as follows:\n\n$$\nP(R_{4}) = \\sum_{i=1}^{9} P(R_{4} | B_{i})P(B_{i})\n$$\n\n$$\nP(R_{4}) = \\frac{1}{10} \\cdot \\sum_{i=1}^{9} \\left(\\frac{i}{9}\\right)^4 = 0.233\n$$\n\nfinally, we can calculate $P(R_{4} | R_{3})$:\n\n$$\nP(R_{4} | R_{3}) = \\frac{1 \\cdot 0.233}{0.277} = 0.84\n$$\n\nWe can simulate this experiment as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-34_bc6d283d2ef044d1c933aaf7f0ded03e'}\n\n```{.r .cell-code}\nevent_a_and_b <- replicate(100000, {\n    box <- sample(x = 0:9, size =1)\n    marbles <- sample(c(rep(\"red\", box), rep(\"blue\", 9 - box)), 4, replace = TRUE)\n    all(marbles == \"red\")\n})\n\nevent_b <- replicate(100000, {\n    box <- sample(x = 0:9, size =1)\n    marbles <- sample(c(rep(\"red\", box), rep(\"blue\", 9 - box)), 3, replace = TRUE)\n    all(marbles == \"red\")\n})\n\nmean(event_a_and_b) / mean(event_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8350382\n```\n:::\n:::\n\n\n### Part (b)\n\nLet's denote the event of choosing box 9 as $B_{9}$. We want to calculate $P(B_{9} | R_{3})$. We can apply Bayes' theorem:\n\n$$\nP(B_{9} | R_{3}) = \\frac{P(R_{3} | B_{9}) \\cdot P(B_{9})}{P(R_{3})}\n$$\n\nThe probability of getting three consecutive red marbles given that we have chosen box 9 is $P(R_{3} | B_{9}) = \\left(\\frac{9}{9}\\right)^3 = 1$. The probability of choosing box 9 is $P(B_{9}) = \\frac{1}{10}$. The probability of getting three consecutive red marbles is $P(R_{3}) = 0.277$. Therefore, we can calculate $P(B_{9} | R_{3})$ as follows:\n\n$$\nP(B_{9} | R_{3}) = \\frac{1 \\cdot \\frac{1}{10}}{0.277} = 0.36\n$$\n\nWe can simulate this experiment as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-35_6d06587f657525c76df306cecb662130'}\n\n```{.r .cell-code}\nevent_a_and_b <- replicate(100000, {\n    box <- sample(x = 0:9, size =1)\n    marbles <- sample(c(rep(\"red\", box), rep(\"blue\", 9 - box)), 3, replace = TRUE)\n    all(marbles == \"red\") && box == 9\n})\n\nevent_b <- replicate(100000, {\n    box <- sample(x = 0:9, size =1)\n    marbles <- sample(c(rep(\"red\", box), rep(\"blue\", 9 - box)), 3, replace = TRUE)\n    all(marbles == \"red\")\n})\n\nmean(event_a_and_b) / mean(event_b)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.363971\n```\n:::\n:::\n\n\n## Problem 2.33\n\n**How many ways are there of getting 4 heads when tossing 10 coins?**\n\nusing the binomial coefficient:\n\n$$\n{10 \\choose 4} = \\frac{10!}{4! \\cdot 6!} = 210\n$$\n\n## Problem 2.34\n\n**How many ways are there of getting 4 heads when tossing 10 coins, assuming that the 4th head came on the 10th toss?**\n\nIf we know that the 4th head came on the 10th toss, then we must have gotten exactly 3 heads in the first 9 tosses. We can count the number of ways to get 3 heads in 9 tosses using the binomial coefficient:\n\n$$\n{9 \\choose 3} = \\frac{9!}{3! \\cdot 6!} = 84\n$$\n\n## Problem 2.35\n\nSix standard six-sided dice are rolled.\n\na. How many outcomes are there?\nb. How many outcomes are there such that all of the dice are different numbers?\nc. What is the probability that you obtain six different numbers when you roll six dice?\n\n### Part (a)\n\nThe number of outcomes is $6^{6} = 46656$\n\n### Part (b)\n\nThe first die can be any of the six numbers. The second die must be one of the remaining five numbers (since we can't repeat the number from the first die), the third die must be one of the remaining four numbers, and so on. Therefore, the number of outcomes in which all six dice are different is:\n\nThe number of outcomes is $6 \\cdot 5 \\cdot 4 \\cdot 3 \\cdot 2 \\cdot 1 = 720$\n\n### Part (c)\n\nThe probability of getting six different numbers when rolling six dice is:\n\n$$\nP(E) = \\frac{720}{46656} = 0.0154\n$$\n\n## Problem 2.36\n\n**A box contains 5 red marbles and 5 blue marbles. Six marbles are drawn without replacement.**\n\na. How many ways are there of drawing the 6 marbles? Assume that getting all 5 red marbles and the first blue marble is different than getting all 5 red marbles and the second blue marble, for example.\nb. How many ways are there of drawing 4 red marbles and 2 blue marbles?\nc. What is the probability of drawing 4 red marbles and 2 blue marbles?\n\n### Part (a)\n\nThe number of ways of drawing 6 marbles is:\n\n$$\n{6 \\choose 10} = \\frac{10!}{6! \\cdot 4!} = 210\n$$\n\n### Part (b)\n\nThe number of ways of drawing 4 red marbles and 2 blue marbles is:\n\n$$\n{5 \\choose 4} \\cdot {5 \\choose 2} = \\frac{5!}{4! \\cdot 1!} \\cdot \\frac{5!}{2! \\cdot 3!} = 50\n$$\n\n### Part (c)\n\nThe probability of drawing 4 red marbles and 2 blue marbles is:\n\n$$\nP(E) = \\frac{50}{210} = 0.238\n$$\n\nWe can simulate this experiment as follow:\n\n\n::: {.cell hash='probability_cache/html/unnamed-chunk-36_83ae9eedcc2a931ae6950c76ca28ba47'}\n\n```{.r .cell-code}\nevent <- replicate(100000, {\n    marbles <- sample(c(rep(\"red\", 5), rep(\"blue\", 5)), 6, replace = FALSE)\n    sum(marbles == \"red\") == 4 && sum(marbles == \"blue\") == 2\n})\n\nmean(event)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.23855\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}