project:
  type: book
  output-dir: _book

execute:
  freeze: auto
  cache: true

website:
  site-url: https://learning.jsantanders.dev
  google-analytics: "G-BL39G9942Y"
  cookie-consent: true
  twitter-card:
    creator: "@jsantanders"
    site: "learning.jsantanders.dev"

book:
  title: "Book's problems and solutions"
  reader-mode: true
  author: "Jesus Santander"
  date: today
  page-footer:
      left: |
        Jesus Santander.
      right: |
        This guide was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://learning.jsantanders.dev
  repo-url: https://github.com/jsantanders/learning.jsantanders.dev/
  repo-branch: main
  favicon: notebook.png
  repo-actions: [edit, issue]
  search: true
  chapters:
    - index.qmd

    - part: Probability, Statistics, and Data
      chapters:
        - probability-statistics-and-data/probability.qmd
        - probability-statistics-and-data/discrete-random-variables.qmd

format:
  bookup-html:
    toc: true
    html-math-method: katex

